-- PLUS 메뉴

DROP TABLE tblPlusMenu;
DROP TABLE tblPlusList;

CREATE TABLE tblPlusMenu (
	id NUMBER PRIMARY KEY,
	menu VARCHAR2(50) NOT NULL
);

CREATE TABLE tblPlusList(
	id NUMBER PRIMARY KEY,
          tblWeeklyMenu_id NUMBER REFERENCES tblWeeklyMenu(id) NOT NULL,
          tblPlusMenu_id NUMBER REFERENCES tblPlusMenu(id) NOT NULL
);

CREATE SEQUENCE seqPlusMenu;
CREATE SEQUENCE seqPlusList;

DROP SEQUENCE seqPlusMenu;
DROP SEQUENCE seqPlusList;

SELECT * FROM tblPlusMenu;
SELECT * FROM tblPlusList order by id;

select * from tblPlusMenu pm
    inner join tblPlusList pl
        on pm.id = pl.tblPlusMenu_id 
            inner join tblWeeklyMenu wm
                on wm.id = pl.tblWeeklyMenu_id
                    where tblWeeklyMenu_id = 1;

commit;

-- PLUS 메뉴
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '고구마샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/딸기D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '메밀차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '콘슬로우');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/오렌지D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '레몬아이스티');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '펜네셀러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/블루베리D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '히비스커스티');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '새우칩');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/요거트D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '포도주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '후르츠황도');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/흑임자D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오미자차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '감자샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/키위D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '옥수수차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '나초칩');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/유자D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '석류주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '꿀토마토');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/사우전D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '시원한보리차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '푸실리샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/파인애플D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '복숭아아이스티');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '수박화채');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/참깨D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '복분자차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '단호박샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/오렌지D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '옥수수차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '바나나칩');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/딸기D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '아이스매실차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '동치미');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/렌치D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '사과주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '라면땅');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/블루베리D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '얼그레이티');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/요거트D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '석류주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '수박화채');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/유자D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '수정과');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '감자샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/파인애플D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '포도주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '마카로니샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/사우전D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '히비스커스티');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '새우칩');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/흑임자D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '레몬아이스티');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '고구마샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/키위D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '녹차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '단호박샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/오렌지D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '보리차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '나초칩');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/블루베리D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오렌지주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '푸실리샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/렌치D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '옥수수차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '후르츠황도');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/딸기D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '석류주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '감자샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/참깨D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '메밀차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '마카로니샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/키위D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '녹차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '라면땅');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/유자D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '복분자차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '고구마샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/사우전D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '포도주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '허니버터감자칩');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/요거트D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '복숭아아이스티');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '콘슬로우샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/파인애플D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '둥글레차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '감자샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/오렌지D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '옥수수차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '새우칩');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/렌치D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '사과주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '콘슬로우');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/딸기D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '요구르트');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '나초칩');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/블루베리D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '석류주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '꿀토마토');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/머스타드D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '매실차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '고구마샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/파인애플D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '둥글레차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '라면땅');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/참깨D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오렌지주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '조각수박');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/키위D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '레몬아이스티');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '수박화채');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/유자D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '수정과');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '고구마샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/사우전D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '포도주스');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '감자샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/파인애플D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '둥글레차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '마카로니샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/키위D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '녹차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '콘슬로우');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/딸기D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '요구르트');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '감자샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/참깨D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '메밀차');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '라면땅');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/블루베리D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '얼그레이티');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '그린샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '단호박샐러드');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '오리엔탈D/오렌지D');
INSERT INTO tblPlusMenu (id, menu) VALUES (seqPlusMenu.nextVal, '보리차');


-- PLUS 메뉴 목록
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 1, 1);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 1, 2);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 1, 3);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 1, 4);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 2, 5);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 2, 6);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 2, 7);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 2, 8);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 3, 9);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 3, 10);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 3, 11);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 3, 12);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 4, 13);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 4, 14);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 4, 15);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 4, 16);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 5, 17);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 5, 18);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 5, 19);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 5, 20);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 6, 21);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 6, 22);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 6, 23);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 6, 24);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 7, 25);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 7, 26);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 7, 27);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 7, 28);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 8, 29);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 8, 30);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 8, 31);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 8, 32);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 9, 33);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 9, 34);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 9, 35);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 9, 36);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 10, 37);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 10, 38);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 10, 39);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 10, 40);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 11, 41);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 11, 42);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 11, 43);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 11, 44);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 12, 45);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 12, 46);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 12, 47);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 12, 48);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 13, 49);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 13, 50);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 13, 51);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 13, 52);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 14, 53);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 14, 54);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 14, 55);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 14, 56);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 15, 57);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 15, 58);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 15, 59);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 16, 60);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 16, 61);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 16, 62);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 16, 63);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 17, 64);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 17, 65);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 17, 66);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 17, 67);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 18, 68);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 18, 69);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 18, 70);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 18, 71);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 19, 72);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 19, 73);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 19, 74);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 19, 75);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 20, 76);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 20, 77);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 20, 78);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 20, 79);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 21, 80);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 21, 81);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 21, 82);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 21, 83);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 22, 84);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 22, 85);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 22, 86);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 22, 87);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 23, 88);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 23, 89);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 23, 90);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 23, 91);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 24, 92);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 24, 93);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 24, 94);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 24, 95);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 25, 96);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 25, 97);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 25, 98);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 25, 99);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 26, 100);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 26, 101);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 26, 102);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 26, 103);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 27, 104);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 27, 105);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 27, 106);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 27, 107);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 28, 108);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 28, 109);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 28, 110);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 28, 111);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 29, 112);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 29, 113);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 29, 114);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 29, 115);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 30, 116);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 30, 117);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 30, 118);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 30, 119);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 31, 120);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 31, 121);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 31, 122);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 31, 123);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 32, 124);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 32, 125);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 32, 126);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 32, 127);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 33, 128);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 33, 129);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 33, 130);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 33, 131);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 34, 132);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 34, 133);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 34, 134);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 34, 135);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 35, 136);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 35, 137);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 35, 138);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 35, 139);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 36, 140);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 36, 141);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 36, 142);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 36, 143);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 37, 144);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 37, 145);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 37, 146);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 37, 147);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 38, 148);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 38, 149);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 38, 150);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 38, 151);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 39, 152);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 39, 153);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 39, 154);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 39, 155);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 40, 156);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 40, 157);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 40, 158);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 40, 159);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 41, 160);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 41, 161);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 41, 162);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 41, 163);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 42, 164);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 42, 165);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 42, 166);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 42, 167);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 43, 168);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 43, 169);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 43, 170);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 43, 171);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 44, 172);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 44, 173);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 44, 174);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 44, 175);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 45, 176);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 45, 177);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 45, 178);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 45, 179);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 46, 180);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 46, 181);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 46, 182);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 46, 183);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 47, 1);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 47, 2);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 47, 3);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 47, 4);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 48, 5);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 48, 6);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 48, 7);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 48, 8);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 49, 9);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 49, 10);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 49, 11);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 49, 12);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 50, 13);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 50, 14);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 50, 15);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 50, 16);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 51, 17);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 51, 18);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 51, 19);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 51, 20);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 52, 21);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 52, 22);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 52, 23);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 52, 24);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 53, 25);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 53, 26);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 53, 27);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 53, 28);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 54, 29);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 54, 30);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 54, 31);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 54, 32);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 55, 33);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 55, 34);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 55, 35);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 55, 36);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 56, 37);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 56, 38);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 56, 39);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 56, 40);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 57, 41);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 57, 42);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 57, 43);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 57, 44);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 58, 45);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 58, 46);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 58, 47);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 58, 48);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 59, 49);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 59, 50);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 59, 51);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 59, 52);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 60, 53);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 60, 54);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 60, 55);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 60, 56);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 61, 57);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 61, 58);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 61, 59);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 62, 60);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 62, 61);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 62, 62);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 62, 63);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 63, 64);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 63, 65);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 63, 66);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 63, 67);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 64, 68);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 64, 69);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 64, 70);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 64, 71);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 65, 72);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 65, 73);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 65, 74);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 65, 75);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 66, 76);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 66, 77);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 66, 78);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 66, 79);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 67, 80);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 67, 81);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 67, 82);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 67, 83);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 68, 84);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 68, 85);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 68, 86);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 68, 87);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 69, 88);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 69, 89);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 69, 90);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 69, 91);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 70, 92);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 70, 93);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 70, 94);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 70, 95);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 71, 96);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 71, 97);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 71, 98);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 71, 99);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 72, 100);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 72, 101);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 72, 102);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 72, 103);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 73, 104);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 73, 105);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 73, 106);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 73, 107);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 74, 108);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 74, 109);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 74, 110);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 74, 111);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 75, 112);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 75, 113);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 75, 114);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 75, 115);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 76, 116);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 76, 117);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 76, 118);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 76, 119);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 77, 120);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 77, 121);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 77, 122);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 77, 123);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 78, 124);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 78, 125);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 78, 126);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 78, 127);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 79, 128);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 79, 129);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 79, 130);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 79, 131);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 80, 132);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 80, 133);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 80, 134);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 80, 135);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 81, 136);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 81, 137);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 81, 138);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 81, 139);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 82, 140);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 82, 141);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 82, 142);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 82, 143);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 83, 144);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 83, 145);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 83, 146);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 83, 147);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 84, 148);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 84, 149);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 84, 150);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 84, 151);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 85, 152);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 85, 153);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 85, 154);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 85, 155);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 86, 156);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 86, 157);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 86, 158);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 86, 159);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 87, 160);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 87, 161);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 87, 162);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 87, 163);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 88, 164);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 88, 165);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 88, 166);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 88, 167);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 89, 168);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 89, 169);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 89, 170);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 89, 171);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 90, 172);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 90, 173);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 90, 174);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 90, 175);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 91, 176);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 91, 177);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 91, 178);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 91, 179);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 92, 180);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 92, 181);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 92, 182);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 92, 183);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 93, 1);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 93, 2);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 93, 3);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 93, 4);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 94, 5);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 94, 6);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 94, 7);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 94, 8);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 95, 9);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 95, 10);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 95, 11);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 95, 12);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 96, 13);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 96, 14);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 96, 15);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 96, 16);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 97, 17);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 97, 18);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 97, 19);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 97, 20);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 98, 21);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 98, 22);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 98, 23);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 98, 24);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 99, 25);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 99, 26);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 99, 27);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 99, 28);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 100, 29);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 100, 30);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 100, 31);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 100, 32);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 101, 33);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 101, 34);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 101, 35);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 101, 36);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 102, 37);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 102, 38);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 102, 39);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 102, 40);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 103, 41);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 103, 42);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 103, 43);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 103, 44);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 104, 45);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 104, 46);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 104, 47);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 104, 48);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 105, 49);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 105, 50);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 105, 51);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 105, 52);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 106, 53);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 106, 54);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 106, 55);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 106, 56);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 107, 57);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 107, 58);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 107, 59);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 108, 60);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 108, 61);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 108, 62);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 108, 63);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 109, 64);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 109, 65);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 109, 66);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 109, 67);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 110, 68);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 110, 69);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 110, 70);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 110, 71);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 111, 72);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 111, 73);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 111, 74);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 111, 75);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 112, 76);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 112, 77);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 112, 78);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 112, 79);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 113, 80);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 113, 81);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 113, 82);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 113, 83);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 114, 84);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 114, 85);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 114, 86);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 114, 87);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 115, 88);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 115, 89);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 115, 90);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 115, 91);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 116, 92);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 116, 93);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 116, 94);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 116, 95);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 117, 96);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 117, 97);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 117, 98);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 117, 99);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 118, 100);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 118, 101);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 118, 102);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 118, 103);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 119, 104);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 119, 105);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 119, 106);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 119, 107);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 120, 108);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 120, 109);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 120, 110);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 120, 111);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 121, 112);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 121, 113);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 121, 114);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 121, 115);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 122, 116);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 122, 117);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 122, 118);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 122, 119);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 123, 120);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 123, 121);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 123, 122);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 123, 123);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 124, 124);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 124, 125);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 124, 126);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 124, 127);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 125, 128);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 125, 129);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 125, 130);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 125, 131);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 126, 132);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 126, 133);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 126, 134);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 126, 135);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 127, 136);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 127, 137);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 127, 138);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 127, 139);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 128, 140);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 128, 141);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 128, 142);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 128, 143);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 129, 144);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 129, 145);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 129, 146);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 129, 147);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 130, 148);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 130, 149);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 130, 150);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 130, 151);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 131, 152);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 131, 153);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 131, 154);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 131, 155);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 132, 156);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 132, 157);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 132, 158);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 132, 159);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 133, 160);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 133, 161);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 133, 162);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 133, 163);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 134, 164);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 134, 165);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 134, 166);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 134, 167);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 135, 168);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 135, 169);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 135, 170);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 135, 171);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 136, 172);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 136, 173);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 136, 174);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 136, 175);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 137, 176);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 137, 177);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 137, 178);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 137, 179);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 138, 180);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 138, 181);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 138, 182);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 138, 183);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 139, 1);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 139, 2);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 139, 3);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 139, 4);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 140, 5);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 140, 6);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 140, 7);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 140, 8);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 141, 9);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 141, 10);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 141, 11);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 141, 12);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 142, 13);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 142, 14);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 142, 15);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 142, 16);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 143, 17);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 143, 18);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 143, 19);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 143, 20);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 144, 21);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 144, 22);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 144, 23);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 144, 24);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 145, 25);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 145, 26);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 145, 27);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 145, 28);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 146, 29);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 146, 30);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 146, 31);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 146, 32);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 147, 33);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 147, 34);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 147, 35);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 147, 36);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 148, 37);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 148, 38);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 148, 39);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 148, 40);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 149, 41);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 149, 42);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 149, 43);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 149, 44);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 150, 45);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 150, 46);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 150, 47);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 150, 48);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 151, 49);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 151, 50);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 151, 51);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 151, 52);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 152, 53);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 152, 54);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 152, 55);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 152, 56);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 153, 57);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 153, 58);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 153, 59);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 154, 60);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 154, 61);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 154, 62);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 154, 63);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 155, 64);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 155, 65);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 155, 66);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 155, 67);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 156, 68);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 156, 69);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 156, 70);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 156, 71);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 157, 72);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 157, 73);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 157, 74);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 157, 75);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 158, 76);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 158, 77);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 158, 78);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 158, 79);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 159, 80);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 159, 81);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 159, 82);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 159, 83);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 160, 84);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 160, 85);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 160, 86);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 160, 87);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 161, 88);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 161, 89);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 161, 90);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 161, 91);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 162, 92);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 162, 93);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 162, 94);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 162, 95);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 163, 96);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 163, 97);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 163, 98);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 163, 99);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 164, 100);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 164, 101);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 164, 102);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 164, 103);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 165, 104);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 165, 105);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 165, 106);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 165, 107);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 166, 108);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 166, 109);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 166, 110);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 166, 111);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 167, 112);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 167, 113);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 167, 114);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 167, 115);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 168, 116);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 168, 117);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 168, 118);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 168, 119);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 169, 120);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 169, 121);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 169, 122);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 169, 123);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 170, 124);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 170, 125);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 170, 126);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 170, 127);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 171, 128);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 171, 129);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 171, 130);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 171, 131);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 172, 132);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 172, 133);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 172, 134);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 172, 135);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 173, 136);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 173, 137);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 173, 138);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 173, 139);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 174, 140);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 174, 141);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 174, 142);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 174, 143);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 175, 144);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 175, 145);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 175, 146);
INSERT INTO tblPlusList (id, tblWeeklyMenu_id, tblPlusMenu_id) VALUES (seqPlusList.nextVal, 175, 147);


