-- 일품
DROP TABLE tblPremiumMenu;
DROP TABLE tblPremiumList;

CREATE TABLE tblPremiumMenu(
	id NUMBER PRIMARY KEY,
	menu VARCHAR2(50) NOT NULL
);

CREATE TABLE tblPremiumList(
	id NUMBER PRIMARY KEY,
          tblWeeklyMenu_id NUMBER REFERENCES tblWeeklyMenu(id) NOT NULL,
          tblPremiumMenu_id NUMBER REFERENCES tblPremiumMenu(id) NOT NULL
);

CREATE SEQUENCE seqPremiumList;
CREATE SEQUENCE seqPremiumMenu;

DROP SEQUENCE seqPremiumList;
DROP SEQUENCE seqPremiumMenu;

SELECT * FROM tblPremiumMenu;
SELECT * FROM tblPremiumList;

select * from tblPremiumMenu pm
    inner join tblPremiumList pl
        on pm.id = pl.tblPremiumMenu_id 
            inner join tblWeeklyMenu wm
                on wm.id = pl.tblWeeklyMenu_id
                    where tblWeeklyMenu_id = 2;


-- 일품 메뉴
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '가츠동(돈가스덮밥)' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '섬초된장국' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '알감자버터구이' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '반달단무지' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '포기김치' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '쌀밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '백소정 냉소바' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '군만두튀김*초간장' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '오복채무침' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '포기김치' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '추가밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '스팸마요덮밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '종합어묵탕' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '모듬감자튀김*케찹' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '마늘쫑지' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '깍두기' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '쌀밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '소세지오므라이스' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '근대된장국' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '김말이튀김*초간장' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '짜사이무침' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '포기김치' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '현미밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '숙주돈가스*소스' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '미역국' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '가래떡떡볶이' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '청상추오리엔탈무침' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '깍두기' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '후리가케밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '마파두부덮밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '파계란국' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '치킨너겟*머스타드' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '반달단무지' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '열무김치' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '현미밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '매운소고기쌀국수' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '모듬춘권튀김' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '청경채굴소스볶음' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '포기김치' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '추가밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '김치말이국수' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '새우가스*칠리소스' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '부추겉절이' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '깍두기' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '추가밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '함박스테이크' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '크림스프' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '샐러드파스타' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '오이피클' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '깍두기' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '현미밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '메추리알카레라이스' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '김치맑은국' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '맛감자튀김*케찹' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '부추겉절이' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '깍두기' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '현미밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '에비텐냉소바' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '찐만두(고기/김치)' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '꼬들단무지' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '포기김치' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '추가밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '가츠동(돈가스덮밥)' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '청양초콩나물국' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '야채튀김*초간장' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '반달단무지' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '포기김치' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '현미밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '미트소스스파게티' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '유부가쓰오국' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '생선가스*타르소스' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '수제모듬피클' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '포기김치' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '추가밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '꼬치어묵우동' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '만두돈가스*케찹' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '오복채무침' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '포기김치' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '추가밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '일식카레라이스' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '가쓰오장국' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '새우가스*칠리소스' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '락교단무지무침' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '포기김치' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '소고기쌀국수' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '피자춘권*칠리소스' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '자차이채무침' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '깍두기' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '후리가케밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '가지솥밥' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '건새우아욱국' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '스모크햄전' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '무말랭이고춧잎무침' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '포기김치' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '비빔막국수' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '멸치장국' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '너비아니' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '깍두기' ); 
INSERT INTO tblPremiumMenu (id, menu) VALUES (seqPremiumMenu.nextVal, '충무김밥' ); 



-- 일품 메뉴 목록
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 2, 1);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 2, 2);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 2, 3);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 2, 4);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 2, 5);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 2, 6);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 4, 7);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 4, 8);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 4, 9);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 4, 10);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 4, 11);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 7, 12);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 7, 13);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 7, 14);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 7, 15);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 7, 16);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 7, 17);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 9, 18);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 9, 19);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 9, 20);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 9, 21);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 9, 22);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 9, 23);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 12, 24);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 12, 25);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 12, 26);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 12, 27);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 12, 28);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 12, 29);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 14, 30);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 14, 31);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 14, 32);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 14, 33);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 14, 34);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 14, 35);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 17, 36);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 17, 37);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 17, 38);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 17, 39);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 17, 40);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 19, 41);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 19, 42);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 19, 43);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 19, 44);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 19, 45);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 22, 46);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 22, 47);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 22, 48);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 22, 49);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 22, 50);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 22, 51);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 24, 52);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 24, 53);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 24, 54);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 24, 55);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 24, 56);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 24, 57);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 27, 58);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 27, 59);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 27, 60);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 27, 61);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 27, 62);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 29, 63);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 29, 64);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 29, 65);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 29, 66);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 29, 67);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 29, 68);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 32, 69);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 32, 70);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 32, 71);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 32, 72);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 32, 73);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 32, 74);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 34, 75);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 34, 76);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 34, 77);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 34, 78);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 34, 79);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 37, 80);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 37, 81);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 37, 82);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 37, 83);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 37, 84);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 39, 85);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 39, 86);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 39, 87);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 39, 88);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 39, 89);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 42, 90);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 42, 91);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 42, 92);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 42, 93);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 42, 94);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 44, 95);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 44, 96);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 44, 97);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 44, 98);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 44, 99);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 47, 1);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 47, 2);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 47, 3);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 47, 4);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 47, 5);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 47, 6);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 49, 7);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 49, 8);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 49, 9);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 49, 10);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 49, 11);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 52, 12);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 52, 13);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 52, 14);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 52, 15);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 52, 16);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 52, 17);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 54, 18);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 54, 19);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 54, 20);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 54, 21);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 54, 22);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 54, 23);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 57, 24);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 57, 25);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 57, 26);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 57, 27);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 57, 28);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 57, 29);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 59, 30);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 59, 31);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 59, 32);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 59, 33);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 59, 34);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 59, 35);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 62, 36);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 62, 37);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 62, 38);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 62, 39);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 62, 40);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 64, 41);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 64, 42);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 64, 43);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 64, 44);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 64, 45);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 67, 46);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 67, 47);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 67, 48);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 67, 49);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 67, 50);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 67, 51);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 69, 52);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 69, 53);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 69, 54);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 69, 55);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 69, 56);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 69, 57);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 72, 58);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 72, 59);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 72, 60);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 72, 61);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 72, 62);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 74, 63);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 74, 64);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 74, 65);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 74, 66);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 74, 67);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 74, 68);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 77, 69);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 77, 70);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 77, 71);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 77, 72);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 77, 73);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 77, 74);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 79, 75);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 79, 76);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 79, 77);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 79, 78);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 79, 79);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 82, 80);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 82, 81);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 82, 82);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 82, 83);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 82, 84);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 84, 85);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 84, 86);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 84, 87);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 84, 88);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 84, 89);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 87, 90);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 87, 91);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 87, 92);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 87, 93);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 87, 94);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 89, 95);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 89, 96);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 89, 97);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 89, 98);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 89, 99);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 92, 1);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 92, 2);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 92, 3);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 92, 4);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 92, 5);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 92, 6);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 94, 7);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 94, 8);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 94, 9);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 94, 10);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 94, 11);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 97, 12);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 97, 13);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 97, 14);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 97, 15);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 97, 16);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 97, 17);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 99, 18);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 99, 19);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 99, 20);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 99, 21);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 99, 22);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 99, 23);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 102, 24);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 102, 25);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 102, 26);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 102, 27);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 102, 28);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 102, 29);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 104, 30);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 104, 31);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 104, 32);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 104, 33);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 104, 34);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 104, 35);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 107, 36);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 107, 37);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 107, 38);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 107, 39);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 107, 40);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 109, 41);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 109, 42);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 109, 43);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 109, 44);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 109, 45);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 112, 46);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 112, 47);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 112, 48);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 112, 49);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 112, 50);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 112, 51);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 114, 52);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 114, 53);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 114, 54);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 114, 55);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 114, 56);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 114, 57);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 117, 58);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 117, 59);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 117, 60);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 117, 61);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 117, 62);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 119, 63);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 119, 64);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 119, 65);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 119, 66);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 119, 67);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 119, 68);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 122, 69);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 122, 70);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 122, 71);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 122, 72);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 122, 73);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 122, 74);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 124, 75);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 124, 76);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 124, 77);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 124, 78);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 124, 79);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 127, 80);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 127, 81);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 127, 82);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 127, 83);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 127, 84);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 129, 85);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 129, 86);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 129, 87);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 129, 88);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 129, 89);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 132, 90);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 132, 91);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 132, 92);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 132, 93);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 132, 94);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 134, 95);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 134, 96);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 134, 97);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 134, 98);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 134, 99);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 137, 1);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 137, 2);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 137, 3);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 137, 4);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 137, 5);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 137, 6);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 139, 7);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 139, 8);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 139, 9);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 139, 10);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 139, 11);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 142, 12);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 142, 13);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 142, 14);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 142, 15);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 142, 16);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 142, 17);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 144, 18);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 144, 19);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 144, 20);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 144, 21);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 144, 22);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 144, 23);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 147, 24);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 147, 25);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 147, 26);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 147, 27);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 147, 28);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 147, 29);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 149, 30);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 149, 31);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 149, 32);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 149, 33);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 149, 34);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 149, 35);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 152, 36);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 152, 37);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 152, 38);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 152, 39);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 152, 40);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 154, 41);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 154, 42);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 154, 43);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 154, 44);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 154, 45);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 157, 46);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 157, 47);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 157, 48);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 157, 49);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 157, 50);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 157, 51);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 159, 52);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 159, 53);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 159, 54);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 159, 55);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 159, 56);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 159, 57);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 162, 58);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 162, 59);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 162, 60);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 162, 61);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 162, 62);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 164, 63);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 164, 64);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 164, 65);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 164, 66);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 164, 67);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 164, 68);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 167, 69);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 167, 70);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 167, 71);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 167, 72);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 167, 73);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 167, 74);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 169, 75);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 169, 76);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 169, 77);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 169, 78);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 169, 79);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 172, 80);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 172, 81);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 172, 82);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 172, 83);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 172, 84);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 174, 85);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 174, 86);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 174, 87);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 174, 88);
INSERT INTO tblPremiumList (id, tblWeeklyMenu_id, tblPremiumMenu_id) VALUES (seqPremiumList.nextVal, 174, 89);





